### ISSUE TITLE
curl resolving timed out

### ISSUE THREAD

**Issue by SosthenG** [thrnz/docker-wireguard-pia#92]
Hi,

Since last update my container stopped working, it seems to have troubles accessing external content.

Here are my logs:
```
Mon Dec 25 14:50:33 UTC 2023: Falling back to iptables-legacy
Fetching next-gen PIA server list
curl: (28) Resolving timed out after 15000 milliseconds
curl: (28) Resolving timed out after 15001 milliseconds
curl: (28) Resolving timed out after 15000 milliseconds
curl: (28) Resolving timed out after 15001 milliseconds
curl: (28) Resolving timed out after 15001 milliseconds
curl: (28) Resolving timed out after 15000 milliseconds
Error reading signature file /tmp/tmp.okDMCp
Failed to verify server list
Mon Dec 25 14:52:28 UTC 2023: Failed to generate WireGuard config
Mon Dec 25 14:52:28 UTC 2023: Fatal error
```

And here is my launch command:
```
#/bin/bash
docker run -d \
  --name pia \
  --cap-add=NET_ADMIN \
  --cap-add=SYS_MODULE \
  --device /dev/net/tun \
  --sysctl net.ipv4.conf.all.src_valid_mark=1 \
  --sysctl net.ipv6.conf.default.disable_ipv6=1 \
  --sysctl net.ipv6.conf.all.disable_ipv6=1 \
  --sysctl net.ipv6.conf.lo.disable_ipv6=1 \
  -p 8282:8112 \
  -p 58846:58846 \
  -p 9117:9117 \
  -p 8191:819 \
  -v /volume1/docker/pia:/pia \
  -v /volume1/docker/pia-port:/pia-shared \
  -e USER=myusername -e PASS='*****' \
  -e LOC=swiss \
  -e LOCAL_NETWORK=192.168.1.0/24 \
  -e VPNDNS="1.1.1.1, 1.0.0.1" \
  -e PORT_FORWARDING=1 \
  -e PORT_PERSIST=1 \
  -e EXIT_ON_FATAL=1 \
  --restart unless-stopped \
  thrnz/docker-wireguard-pia:latest
```

I haven't touched this launch command in a while and it worked fine until now. I tried to remove the custom VPNDNS to use default but the issue is the same. I also tried to remove the token file to force new authentication but the same curl error happened.
Finally I tried running the same launch command on a classic linux server (Debian 11) and it started fine without any issue.

I'm running the container on a Synology NAS DS418Play on version DSM 7.1.1-42962. The docker image version is the latest and I cannot find the previous ones on the docker hub so ~~I cannot rollback~~ **EDIT : I found an old testing version of this container that I still had since #31 and it works fine with it. So It probably has something to do with the latest changes you made regarding iptables I guess.**

Thanks!

**Comment by thrnz** [comment]
Thanks for the logs. Alpine changed some iptables related stuff (it now uses `iptables-nft` rather than `iptables-legacy` by default) in their 3.19 release which seems to be causing issues with the container on certain setups. The container uses the latest Alpine release, so things would have likely broken when the container was rebuilt and pushed to docker hub for the first time using 3.19 a week or so ago.

I tried to catch and revert to using `iptables-legacy` as needed in #91, though it looks like its still missing something.

Could you try running the testing tagged docker hub build: `thrnz/docker-wireguard-pia:testing`? It should show any iptables related errors in the logs which might help to nail down whats going wrong.

**Comment by SosthenG** [comment]
Thanks for your quick answer.
Here are the logs with the latest testing version:
```
# Warning: iptables-legacy tables present, use iptables-legacy to see them
iptables v1.8.10 (nf_tables): Could not fetch rule set generation id: Invalid argument
Tue Dec 26 11:31:53 UTC 2023: Using iptables-legacy
Fetching next-gen PIA server list
curl: (28) Resolving timed out after 15000 milliseconds
curl: (28) Resolving timed out after 15000 milliseconds
curl: (28) Resolving timed out after 15000 milliseconds
curl: (28) Resolving timed out after 15000 milliseconds
curl: (28) Resolving timed out after 15000 milliseconds
curl: (28) Resolving timed out after 15000 milliseconds
Error reading signature file /tmp/tmp.PnCGLn
Failed to verify server list
Tue Dec 26 11:33:48 UTC 2023: Failed to generate WireGuard config
Tue Dec 26 11:33:48 UTC 2023: Fatal error
```

**Comment by relains** [comment]
Hi, same problem for me. Below is the output. I'm running the container on UNRAID.

```
Fetching next-gen PIA server list
curl: (28) Resolving timed out after 15002 milliseconds
curl: (28) Resolving timed out after 15002 milliseconds
curl: (28) Resolving timed out after 15015 milliseconds
curl: (28) Resolving timed out after 15002 milliseconds
curl: (28) Resolving timed out after 15001 milliseconds
curl: (28) Resolving timed out after 15002 milliseconds
Error reading signature file /tmp/tmp.jPDBOC
Failed to verify server list
Tue Dec 26 17:38:22 UTC 2023: Failed to generate WireGuard config
Tue Dec 26 17:38:22 UTC 2023: Fatal error
```

**Comment by thrnz** [comment]
Nothing stands out iptables wise in those logs. It looks like its falling back to legacy and not throwing any more errors. Functionally it should be the same as it was before in 3.18.

I've updated the testing branch to use 3.18. Is that enough to get things working again?

**Comment by thrnz** [comment]
It looks like curl had a dns-related change in Alpine 3.19 that wasn't included in 3.18, despite both being the same version of curl. I wonder if that might be related.

Is there any difference when running `curl https://serverlist.piaservers.net/` and `wget https://serverlist.piaservers.net/` in an affected container?

**Comment by SosthenG** [comment]
**It works fine with the latest testing branch!**

I also checked the difference between curl and wget in the latest branch as requested and I can confirm the issue seems to come from curl. wget returns almost instantly a 404 while curl cannot resolve the host:
```
94da6ab4c83f:/scripts# wget https://serverlist.piaservers.net/
Connecting to serverlist.piaservers.net (104.16.114.56:443)
wget: server returned error: HTTP/1.1 404 Not Found
94da6ab4c83f:/scripts# curl https://serverlist.piaservers.net/
curl: (6) Could not resolve host: serverlist.piaservers.net
94da6ab4c83f:/scripts#
```

**Comment by thrnz** [comment]
I've rebuilt the testing branch using a later version of the library that might be causing the curl issue just to see if its something that's already been fixed. Let me know how it goes.

It might be worth checking that the vpn routing is still working with that first iptables error, though I think `wg-quick` usually dies if something fatal happens. Does mounting `/lib/modules` by adding `-v /lib/modules:/lib/modules` to the command line fix it?

The second iptables error is probably benign if things are still working as expected.

**Comment by thrnz** [comment]
Excellent! Thanks for the testing. I've merged a temporary fix that I'll remove once the fixed version of the c-ares library makes it way to Alpine 3.19. It appears to be broken in 1.22 and fixed in 1.24.

I'll leave this issue open until then as I'll need confirmation that it's still fixed when that happens.

**Comment by thrnz** [comment]
It looks like the fixed version of the library is now included in Alpine 3.19. I've rebuilt the testing branch with the temporary fix removed, though it'll need testing to make sure that its still working as expected.

**Comment by SosthenG** [comment]
I can confirm it still works fine after pulling the testing branch.
I still see this in the logs but as you said before it's not a big deal as it's working fine:
```
iptables-restore v1.8.10 (legacy): iptables-restore: unable to initialize table 'raw'
Error occurred at line: 1
```

Thanks for your work!
